# Generated by Django 5.2.1 on 2025-06-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='ID do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do Instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe p nome do Instrutor', max_length=100)),
                ('data_nascimento', models.DateField(help_text='Informe a data de nascimento')),
                ('telefone', models.CharField(help_text='Informe o telefone do Instrutor', max_length=9)),
                ('ddd', models.CharField(help_text='Informe o DDD do Instrutor', max_length=3)),
            ],
        ),
    ]
