# Generated by Django 5.2.1 on 2025-06-09 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0005_alter_instrutor_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 22, 57, 59, 505585, tzinfo=datetime.timezone.utc), help_text='Informe a data de nascimento', null=True),
        ),
    ]
