# Generated by Django 5.2.1 on 2025-06-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Entre com a Matricula do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe p nome do Aluno', max_length=70)),
                ('data_inicial', models.DateField(verbose_name='Informe a data de Matricula')),
                ('data_fim', models.DateField(verbose_name='Informe Data final do Aluno')),
            ],
        ),
    ]
