# Generated by Django 5.2.1 on 2025-06-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(help_text='Informe p nome do Aluno', max_length=100),
        ),
    ]
