# Generated by Django 5.2.1 on 2025-06-06 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Informe Data final do Aluno na escola', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 6, 22, 10, 17, 481678, tzinfo=datetime.timezone.utc), help_text='Informe a data de Matricula na escola'),
        ),
    ]
