# Generated by Django 5.2.1 on 2025-06-09 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_aluno_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 22, 6, 28, 470723, tzinfo=datetime.timezone.utc), help_text='Informe a data de Matricula na escola'),
        ),
    ]
