# Generated by Django 5.2.1 on 2025-06-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Numero da turma', primary_key=True, serialize=False)),
                ('duracao', models.SmallIntegerField(help_text='Informe a duração da turma')),
                ('horario_aula', models.TimeField(help_text='Informe o horario da aula')),
                ('data_inicial', models.DateField(help_text='Informe a data inicial da turma')),
                ('data_final', models.DateField(help_text='Informe a data final da turma')),
            ],
        ),
    ]
