# Generated by Django 5.2.1 on 2025-06-07 00:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_aluno_data_inicial'),
        ('instrutor', '0003_alter_instrutor_data_nascimento'),
        ('tiposdeatividade', '0002_alter_tipodeatividade_descricao'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='tiposdeatividade.tipodeatividade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='instrutor.instrutor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='matricula_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_final',
            field=models.DateField(blank=True, help_text='Informe a data final da turma', null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 7, 0, 5, 2, 856999, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da turma', null=True),
        ),
    ]
