# Generated by Django 5.2.1 on 2025-06-09 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_turma_codigo_atividade_turma_id_instrutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 22, 6, 28, 470723, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da turma', null=True),
        ),
    ]
