# Generated by Django 5.2.1 on 2025-06-09 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0003_alter_turma_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 22, 47, 40, 867878, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da turma', null=True),
        ),
    ]
